# /etc/nginx/conf.d/custom.conf

server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;
    error_page 404 /error.html;
    location / { try_files $uri $uri/ =404; }
    location = /error.html { internal; }
}

server {
    listen 8080;
    root /usr/share/nginx/html/app1;
    index index.html;
    error_page 404 /error.html;
    location / { try_files $uri $uri/ =404; }
    location = /error.html { internal; }
}

server {
    listen 8081;
    root /usr/share/nginx/html/app2;
    index index.html;
    error_page 404 /error.html;
    location / { try_files $uri $uri/ =404; }
    location = /error.html { internal; }
}
