events { }

http {
    # Root app on port 80
    server {
        listen 80;
        server_name localhost;

        root /usr/share/nginx/html;
        index index.html;

        error_page 404 /error.html;

        location / {
            try_files $uri $uri/ =404;
        }

        location = /error.html {
            internal;
        }
    }

    # App1 on port 8080
    server {
        listen 8080;
        server_name localhost;

        root /usr/share/nginx/html/app1;
        index index.html;

        error_page 404 /error.html;

        location / {
            try_files $uri $uri/ =404;
        }

        location = /error.html {
            internal;
        }
    }

    # App2 on port 8081
    server {
        listen 8081;
        server_name localhost;

        root /usr/share/nginx/html/app2;
        index index.html;

        error_page 404 /error.html;

        location / {
            try_files $uri $uri/ =404;
        }

        location = /error.html {
            internal;
        }
    }
}
